SELECT DISTINCT
	case when ( WISE2_DWH_dbo_DT_LOGO_GLOBAL_V2_USER.LGB_SOURCE_NAME_FK ) in ('W1','W2','CMB','BS') then ( WISE2_DWH_dbo_DT_LOGO_GLOBAL_V2_USER.LGB_REF ) else ( WISE2_DWH_dbo_DT_LOGO_GLOBAL_V2_USER.LGB_SOURCE_ID ) end as GlobalLogoRef,
	WISE2_DWH_dbo_DT_LOGO_GLOBAL_V2_USER.LGB_NAME as GlobalLogoName,
	case when ( WISE2_DWH_dbo_DT_LOGO_V2_USER.LOG_SOURCE_NAME_FK ) in ('W1','W2','CMB','BS') then ( WISE2_DWH_dbo_DT_LOGO_V2_USER.LOG_REF ) else ( WISE2_DWH_dbo_DT_LOGO_V2_USER.LOG_SOURCE_ID ) end as LogoRef,
	WISE2_DWH_dbo_DT_LOGO_V2_USER.LOG_NAME as LogoName,
	DT_SUBSIDIARY_USER.SUB_NAME as Subsidiary,
	DT_BILLING_ACCOUNT_USER.BILACC_REF as ClientRef,
	DT_BILLING_ACCOUNT_USER.BILACC_NAME as ClientName,
	DT_OFFER_BILACC_USER_V2.OFF_NAME as ClientOfferName,
	dbo.DT_PRIM_GROUP.PGP_REF as PrimaryGroupRef,
	CASE WHEN dbo.DT_PRIM_GROUP.PGP_SOURCE_NAME_FK = 'W2' THEN  dbo.DT_PRIM_GROUP.PGP_EXT_REF ELSE NULL END as PrimaryGroupId,
	dbo.DT_PRIM_GROUP.PGP_NAME as PrimaryGroupName,
	DT_BILLING_ACCOUNT_USER.BILACC_SOURCE_NAME_FK as ClientSourceName,
	dbo.DT_PRIM_GROUP.PGP_REAL_CREATION_DATE as SiteCreationDate,
	DT_BILLING_ACCOUNT_USER.BILACC_IS_DELETED as IsDeleted
FROM
	dbo.DT_SUBSIDIARY  DT_SUBSIDIARY_USER INNER JOIN dbo.DT_BILLING_ACCOUNT  DT_BILLING_ACCOUNT_USER ON (DT_BILLING_ACCOUNT_USER.BILACC_SUB_REF=DT_SUBSIDIARY_USER.SUB_CODE)
	RIGHT OUTER JOIN dbo.DT_PRIM_GROUP ON (dbo.DT_PRIM_GROUP.PGP_BILACC_FK=DT_BILLING_ACCOUNT_USER.BILACC_PK)
	RIGHT OUTER JOIN dbo.DT_USER ON (dbo.DT_PRIM_GROUP.PGP_ID_PK=dbo.DT_USER.USE_PGP_ID_FK)
	LEFT OUTER JOIN dbo.DT_LOGO_V2  WISE2_DWH_dbo_DT_LOGO_V2_USER ON (DT_BILLING_ACCOUNT_USER.BILACC_REF=WISE2_DWH_dbo_DT_LOGO_V2_USER.LOG_BILACC_REF AND DT_BILLING_ACCOUNT_USER.BILACC_SOURCE_NAME_FK=WISE2_DWH_dbo_DT_LOGO_V2_USER.LOG_SOURCE_NAME_FK)
	LEFT OUTER JOIN dbo.DT_LOGO_GLOBAL_V2  WISE2_DWH_dbo_DT_LOGO_GLOBAL_V2_USER ON (WISE2_DWH_dbo_DT_LOGO_V2_USER.LOG_LGB_SOURCE_ID=WISE2_DWH_dbo_DT_LOGO_GLOBAL_V2_USER.LGB_SOURCE_ID AND WISE2_DWH_dbo_DT_LOGO_V2_USER.LOG_SOURCE_NAME_FK=WISE2_DWH_dbo_DT_LOGO_GLOBAL_V2_USER.LGB_SOURCE_NAME_FK)
	LEFT OUTER JOIN dbo.ARKA_DT_BIL_ACC_OFFER  DT_BIL_ACC_USER_OFFER ON (DT_BIL_ACC_USER_OFFER.OFF_BILACC_PK=DT_BILLING_ACCOUNT_USER.BILACC_PK)
	LEFT OUTER JOIN dbo.DT_OFFER_V2  DT_OFFER_BILACC_USER_V2 ON (DT_BIL_ACC_USER_OFFER.OFF_OFF_PK=DT_OFFER_BILACC_USER_V2.OFF_ID)
WHERE
(
	DT_BILLING_ACCOUNT_USER.BILACC_SOURCE_NAME_FK  =  N'W2' AND
	DT_SUBSIDIARY_USER.SUB_NAME not in ('Arkadin Orson') AND
	DT_PRIM_GROUP.PGP_EXT_REF IS NOT NULL
)